### ISSUE TITLE
Upon submission of VC, Runtime Exception is thrown

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#27]
https://beta-vcr.clarin.eu/app/create?14-5.IFormSubmitListener-form

{{{

Unexpected RuntimeException

Last cause: Target host is nullWicketMessage: Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener targeted at [Form [Component id = form]] on component [Form [Component id = form]] threw an exception
--

Stacktrace

Root cause:

java.lang.IllegalStateException: Target host is null
     at org.apache.http.util.Asserts.notNull(Asserts.java:52)
     at org.apache.http.impl.conn.DefaultHttpRoutePlanner.determineRoute(DefaultHttpRoutePlanner.java:100)
     at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:761)
     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:380)
     at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
     at eu.clarin.cmdi.virtualcollectionregistry.service.impl.HttpResponseValidator.checkValidityOfUri(HttpResponseValidator.java:76)
     at eu.clarin.cmdi.virtualcollectionregistry.service.impl.HttpResponseValidator.validate(HttpResponseValidator.java:43)
     at eu.clarin.cmdi.virtualcollectionregistry.service.impl.ReferenceValidator.validate(ReferenceValidator.java:72)
     at eu.clarin.cmdi.virtualcollectionregistry.service.impl.ReferenceValidator.validate(ReferenceValidator.java:45)
     at eu.clarin.cmdi.virtualcollectionregistry.service.impl.VirtualCollectionValidatorImpl.getInvalidReferences(VirtualCollectionValidatorImpl.java:127)
     at eu.clarin.cmdi.virtualcollectionregistry.service.impl.VirtualCollectionValidatorImpl.validate(VirtualCollectionValidatorImpl.java:64)
     at eu.clarin.cmdi.virtualcollectionregistry.VirtualCollectionRegistryImpl.createVirtualCollection(VirtualCollectionRegistryImpl.java:144)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:508)
     at com.sun.proxy.$Proxy101.createVirtualCollection(Unknown Source)
     at eu.clarin.cmdi.virtualcollectionregistry.gui.pages.CreateAndEditVirtualCollectionPage.persist(CreateAndEditVirtualCollectionPage.java:321)
     at eu.clarin.cmdi.virtualcollectionregistry.gui.pages.CreateAndEditVirtualCollectionPage.access$100(CreateAndEditVirtualCollectionPage.java:59)
     at eu.clarin.cmdi.virtualcollectionregistry.gui.pages.CreateAndEditVirtualCollectionPage$FormBuilder$1.onSubmit(CreateAndEditVirtualCollectionPage.java:163)
     at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1316)
     at org.apache.wicket.markup.html.form.Form.process(Form.java:976)
     at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:797)
     at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:708)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
     at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:241)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:234)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     at eu.clarin.cmdi.virtualcollectionregistry.gui.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:29)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     at eu.clarin.cmdi.virtualcollectionregistry.rest.PersistenceFilter.doFilter(PersistenceFilter.java:34)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     at de.mpg.aai.shhaa.AuthFilter.doFilter(AuthFilter.java:84)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.lang.Thread.run(Thread.java:748)

Complete stack:

org.apache.wicket.WicketRuntimeException: Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener targeted at [Form [Component id = form]] on component [Form [Component id = form]] threw an exception
     at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:268)
     at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:241)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:234)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)

java.lang.reflect.InvocationTargetException
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
     at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:241)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:234)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)

}}}

**Comment by WillemElbers** [comment]
I tried locally with both `http://hdl.handle.net/123/456789` and `hdl:123/456789` and cannot reproduce the issue. Do you remember what value you used for the resource reference?

**Comment by WillemElbers** [comment]
Unable to reproduce, confirmed I can create a collection with resources with handles, dois and urn:nbns in both URN and URI format. Closing for now.

**Comment by WillemElbers** [comment]
Figured out how to reproduce this: input a handle (or url) without scheme, so `11022/0000-0000-2417-E` instead of `hdl:11022/0000-0000-2417-E`.

Error handling is been improved and an exception is not thrown anymore. However, the message displayed `one or more references are not valid: [11022/0000-0000-2417-E]`, leaves room for improvement. This is related to https://github.com/clarin-eric/VirtualCollectionRegistry/issues/2. Leaving open for now.
